Repository astronomy-club-at-nitic/nitic-astronomy, pull requests merged in 2023-04, with the labels that each got.

#67 `typescript` v5.5 で非推奨となる `tsconfig.json` のプロパティへの警告を無効化
  apps/website/tsconfig.json
Labels: 🔧 config

#78 `.vscode/settings.json` から `jest.rootPath` の設定を削除
  .vscode/settings.json
Labels: 🐛 bug, 🔧 config

#83 `eslint` にてバグがあるとみられる rules を一部無効化
  apps/website/.eslintrc.json
Labels: 🐛 bug, 🔧 config

#82 `RootLayout` をサーバーコンポーネント化
  apps/website/src/app/layout.tsx
  apps/website/src/core/provider/context.provider.tsx
  apps/website/src/core/provider/page-transition-animation.provider.tsx
  apps/website/src/core/provider/theme.provider.tsx
Labels: ♻ refactor

#91 余計なログ出力が出る問題を解決するために、`tw-colors`を`1.2.2`にアップデートした。
  apps/website/package.json
  pnpm-lock.yaml
Labels: 🐛 bug, 📦️ build

#94 MicroCMSからのデータフェッチを担うパッケージ`cms`を作成した
  .github/workflows/app-test.yaml
  .vscode/settings.json
  apps/website/package.json
  apps/website/src/env.ts
  nitic-astronomy.code-workspace
  package.json
  packages/cms/.env.template
  packages/cms/.eslintignore
  packages/cms/.eslintrc.json
  packages/cms/.lintstagedrc.js
  packages/cms/.prettierignore
  packages/cms/.prettierrc.js
  packages/cms/index.ts
  packages/cms/jest.config.js
  packages/cms/package.json
  packages/cms/src/converter/article.converter.ts
  packages/cms/src/converter/image.converter.ts
  packages/cms/src/converter/member.converter.ts
  packages/cms/src/converter/tag.converter.ts
  packages/cms/src/env.ts
  packages/cms/src/infra/client.factory.ts
  packages/cms/src/infra/microcms.type.ts
  packages/cms/src/model/article.model.ts
  packages/cms/src/model/id.model.ts
  packages/cms/src/model/image.model.ts
  packages/cms/src/model/member.model.ts
  packages/cms/src/model/tag.model.ts
  packages/cms/src/service/article/get-article-detail.service.spec.ts
  packages/cms/src/service/article/get-article-detail.service.ts
  packages/cms/src/service/article/get-article-ids.service.spec.ts
  packages/cms/src/service/article/get-article-ids.service.ts
  packages/cms/src/service/article/get-articles.service.spec.ts
  packages/cms/src/service/article/get-articles.service.ts
  packages/cms/src/service/member/get-members.service.spec.ts
  packages/cms/src/service/member/get-members.service.ts
  packages/cms/src/service/tag/get-tag-detail.service.spec.ts
  packages/cms/src/service/tag/get-tag-detail.service.ts
  packages/cms/src/service/tag/get-tag-ids.service.spec.ts
  packages/cms/src/service/tag/get-tag-ids.service.ts
  packages/cms/src/service/tag/get-tags.service.spec.ts
  packages/cms/src/service/tag/get-tags.service.ts
  packages/cms/tsconfig.build.json
  packages/cms/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ feature, 📦️ build

#120 画像アセットの圧縮用スクリプト`pnpm asset:optimize`を`website`に追加した。
  apps/website/package.json
  apps/website/public/favicon.png
  pnpm-lock.yaml
Labels: 📦️ build, 🍱 asset
