Repository astronomy-club-at-nitic/nitic-astronomy, pull requests merged in 2023-03, with the labels that each got.

#4 `node`と`pnpm`バージョンを厳密に固定した
  .github/workflows/app-build.yaml
  .github/workflows/app-format.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-style.yaml
  .github/workflows/app-test.yaml
  .github/workflows/website-chromatic.yaml
  .npmrc
  package.json
Labels: 🦺 ci, 🔧 config

#8 chore: 🔧 (renovate) `pnpm` のアップデートを automerge しないように修正
  renovate.json
Labels: 🔧 config

#11 `pnpm` を renovate の automerge に含めるように修正
  package.json
  renovate.json
Labels: 🔧 config

#13 chore: 🔨 (package) preinstallを削除
  package.json
Labels: 🐛 bug, 🔧 config

#14 カラースキーム対応のカラーパレットを`next-themes`を使いTailwindに設定した
  apps/website/package.json
  apps/website/src/app/layout.tsx
  apps/website/src/app/page.tsx
  apps/website/src/core/provider/theme.provider.tsx
  apps/website/src/style/token/core.json
  apps/website/src/style/token/dark.json
  apps/website/src/style/token/light.json
  apps/website/tailwind.config.js
  pnpm-lock.yaml
Labels: ✨ feature, 📦️ build

#17 `next-themes` `tailwindcss` `tailwind-scrollbar`の依存関係区分を正しいものに修正した。
  .npmrc
  apps/website/package.json
  pnpm-lock.yaml
Labels: 🐛 bug, 📦️ build, 🔧 config
